# Generated by Django 3.0.5 on 2020-06-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('contact', models.BigIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('picture', models.ImageField(blank=True, default='student1.png', upload_to='')),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
    ]
